version: 2
jobs:
    build-10:
        docker:
            - image: circleci/node:8
            - image: redis
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: npm install
            - run: 
                name: Linter
                command: npm run lint
            - run:
                name: Tests
                command: npm test
            - run:
                name: codecoverage
                command: npm run coverage
    build-8: 
        docker:
            - image: circleci/node:8
            - image: redis
        steps:
            - checkout
            - run:
                name: Install dependencies
                command: npm install
            - run: 
                name: Linter
                command: npm run lint
            - run:
                name: Tests
                command: npm test
workflows:
    version: 2
    build:
        jobs:
            - build-10
            - build-8
