version: 2
jobs:
    build-test:
        docker:
            - image: circleci/node:8
            - image: redis
        steps:
            - checkout
            - run:
                name: install-dependencies
                command: npm install
            - run:
                name: tests
                command: npm test
workflows:
    version: 2
    build-deploy:
        jobs:
            - build-test